# Generated by Django 3.0.8 on 2020-08-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('image', models.ImageField(upload_to='')),
                ('desc', models.TextField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
