# Generated by Django 3.0.8 on 2020-08-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200804_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rec',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='rec',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
