# Generated by Django 3.0.8 on 2020-08-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200804_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
