# Generated by Django 3.0.8 on 2020-08-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200804_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rece',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
