# Generated by Django 3.0.8 on 2020-08-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200804_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rece',
            name='name',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
