# Generated by Django 3.0.8 on 2020-08-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200804_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rece',
            new_name='receipe',
        ),
    ]
